// next-env.d.ts supplies these globally, but it is generated by `next build`
// and gitignored, so `npm run typecheck` would fail on a fresh clone before a
// build has run. Declaring the reference here keeps static image imports
// (components/Hero.tsx) typed regardless of build order.
/// <reference types="next/image-types/global" />
